## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
remote: origin
target-branch: main
chart-dirs:
- charts
chart-repos:
  - grafana=https://grafana.github.io/helm-charts
  - opencost=https://opencost.github.io/opencost-helm-chart
  - opentelemetry=https://open-telemetry.github.io/opentelemetry-helm-charts
  - prometheus-community=https://prometheus-community.github.io/helm-charts
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
exclude-deprecated: true
excluded-charts: []
