{{ define "otelcollector.config.opencost" }}
- job_name: integrations/kubernetes/opencost
  kubernetes_sd_configs:
    - role: service
  relabel_configs:
{{- if .Values.opencost.enabled }}
    - action: keep
      source_labels: ["__meta_kubernetes_service_label_app_kubernetes_io_instance"]
      regex: "{{ .Release.Name }}"
{{- end }}
{{- range $k, $v := .Values.metrics.cost.labelMatchers }}
    - action: keep
      source_labels: ["__meta_kubernetes_service_label_{{ $k | replace "." "_" | replace "/" "_" }}"]
      regex: "{{ $v }}"
{{- end }}
    - action: keep
      source_labels: ["__meta_kubernetes_service_port_name"]
      regex: "http"
{{- if .Values.metrics.cost.allowList }}
  metric_relabel_configs:
    - action: keep
      source_labels: ["__name__"]
      regex: "up|{{ join "|" .Values.metrics.cost.allowList }}"
{{- end }}
{{ end }}
